default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: helpdesk_development
  host: localhost
  username: postgres
  host: localhost
  username: postgres
  database: helpdesk_test
