---
- name: ensure httplib2 is installed
  apt: pkg=python-httplib2 state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  sudo: True
  sudo_user: root

- include: 'rvm.yml'
- include: 'rubies.yml'
